### ISSUE TITLE
Not all Mocha Tests are executed

### ISSUE THREAD

**Issue by gamedevtutorials** [mockoon/commons-server#26]
**Describe the bug**
When you start the npm task test, it will only run the tests inside the spec files which are inside a subfolder of test (like test/templating-helpers/helpers.spec.ts but not the spec files which are directly inside the test folder

**To Reproduce**
npm run test and check the executed tests

**Expected behavior (solution)**
All tests should be executed. An easy fix would be to create subfolders for the utils.spec.ts and the response-rules-interpreter.spec.ts

**Mockoon version:**
Server Version 2.10.0

**OS / OS version:**
Tested on Mac OS

**Comment by 255kb** [comment]
Thank you for spotting this. Strangely this do not happen on Windows.
I will fix this on the main branch
