### ISSUE TITLE
Implements `Number.toFixed()` as a helper 

### ISSUE THREAD

**Issue by 255kb** [mockoon/commons-server#31]
**Is your feature request related to a problem? Please describe.**
There is currently no way to define the number of digits after the decimal point. 

**Describe the solution you'd like**
Implements `Number.toFixed()` as a helper 
An example: https://github.com/helpers/handlebars-helpers/blob/master/lib/number.js#L153

**Comment by roybarber** [comment]
Thanks for this guys, makes a huge difference for mocking E-commerce using templating calculations
