### ISSUE TITLE
Helper "switch/case" doesn't work with number variables

### ISSUE THREAD

**Issue by Ace-Lightning** [mockoon/commons-server#37]
**Describe the bug**
Helper `switch` doesn't work with variable `@index` from helper `repeat`. It returns error:

```
Error while serving the content: (lookupProperty(...) || (data && lookupProperty(...)) || alias2).call is not a function
```

**To Reproduce**
```
[
  {{#repeat 4}}
    { 
      "id": {{@index}}, 
      "name": 
        {{#switch (@index)}}
          {{#case 0}}"John"{{/case}}
          {{#case 1}}"Jack"{{/case}}
          {{#default}}"Peter"{{/default}}
        {{/switch}}
    }
  {{/repeat}}
]
```

**Expected behavior**
It should return follow response:

```
[
  {
    "id": 0,
    "name": "John"
  },
  {
    "id": 1,
    "name": "Jack"
  },
  {
    "id": 2,
    "name": "Peter"
  },
  {
    "id": 3,
    "name": "Peter"
  }
]
```

**Mockoon version:**
1.16.0

**OS / OS version:**
Windows 11

**Comment by 255kb** [comment]
I think you shouldn't use parentheses when using `@index`, instead use them directly: `{{#switch @index}}`. This should return this:
```
[
  {
    "id": 0,
    "name": "Peter"
  },
  {
    "id": 1,
    "name": "Peter"
  },
  {
    "id": 2,
    "name": "Peter"
  },
  {
    "id": 3,
    "name": "Peter"
  }
]
```

As you can see it's kind of working, but there is another bug. Looking at the code it seems that the `switch/case` helper was never tested with numbers. 
I will update the issue and try to solve this for the next release.
